# This is a basic workflow to help you get started with Actions

name: Run benchmark

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Setup MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      
      - name: install dependencies
        run: |
          npm install
          mongo async-benchmark --eval 'db.products.insert({ean: 9780471117094, name: "Pen"}); db.products.insert({ean: 4006381333931, name: "Pencil"}); db.products.createIndex({ean: 1})'
        
      - name: run benchmark
        run: npm start >> result.txt
        
      - name: commit result
        run: |
          git add result.txt
          git config user.name 'Github Actions'
          git config user.email '<>'
          git commit -m "Benchmark"
          
      - name: push benchmark changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
